/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package blackMidnight.ui_forTests;

import blackMidnight.DAO_forTests.UserDAO_Test;
import blackMidnight.controller_forTests.RegisterUserController_forTests;
import blackMidnight.model_forTests.User_Test;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Ilias
 */
public class MainFormStoreOwner_forTests extends javax.swing.JFrame {

    static UserDAO_Test ud = new UserDAO_Test();
    static User_Test user ;
    /**
     * Creates new form MainFormStoreOwner_forTests
     */
    public MainFormStoreOwner_forTests() {
        initComponents();
    }
    
    public MainFormStoreOwner_forTests(String username) {
        initComponents();
        user = ud.userReturnForTests(ud.userIdReturnForTests(username));
        jL_Username.setText(username);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        storeManagementBtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jStoreButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jEditUserButton = new javax.swing.JButton();
        jDeleteUserButton = new javax.swing.JButton();
        jL_Username = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        storeManagementBtn.setText("Store Management");
        storeManagementBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                storeManagementBtnMouseClicked(evt);
            }
        });
        storeManagementBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                storeManagementBtnActionPerformed(evt);
            }
        });

        jButton1.setText("Show Reservation History");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jStoreButton.setText("Add Store");
        jStoreButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jStoreButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Welcome ");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jEditUserButton.setText("Edit User");
        jEditUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEditUserButtonActionPerformed(evt);
            }
        });

        jDeleteUserButton.setText("Delete User");
        jDeleteUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDeleteUserButtonActionPerformed(evt);
            }
        });

        jL_Username.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jL_Username.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jL_Username.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jL_Username, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jStoreButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(storeManagementBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jEditUserButton, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDeleteUserButton, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jL_Username, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jStoreButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDeleteUserButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(storeManagementBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jEditUserButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void storeManagementBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_storeManagementBtnMouseClicked
        // TODO add your handling code here:
        StoreManagementForm_forTests smForm;
        try{
            smForm = new StoreManagementForm_forTests(jL_Username.getText());
            smForm.setVisible(true);
            this.setVisible(false);
        }catch(Exception ex){
            Logger.getLogger(MainFormStoreOwner_forTests.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_storeManagementBtnMouseClicked

    private void storeManagementBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_storeManagementBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_storeManagementBtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        ReservationShowHistoryForm_forTests srhform;
        try {
            srhform = new ReservationShowHistoryForm_forTests();
            srhform.setVisible(true);
            this.setVisible(false);
        } catch (Exception ex) {
            Logger.getLogger(MainFormStoreOwner_forTests.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jStoreButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jStoreButtonActionPerformed
        // TODO add your handling code here:
        CreateStoreForm_forTests csform = new CreateStoreForm_forTests();
        csform.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jStoreButtonActionPerformed

    private void jEditUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEditUserButtonActionPerformed
        // TODO add your handling code here:
        EditUserForm_forTests euf;
        try {
            euf = new EditUserForm_forTests(user);
            euf.setVisible(true);
            this.setVisible(false);
        } catch (NullPointerException ex) {
            Logger.getLogger(MainFormStoreOwner_forTests.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jEditUserButtonActionPerformed

    private void jDeleteUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDeleteUserButtonActionPerformed
        // TODO add your handling code here:
        RegisterUserController_forTests ruc = new RegisterUserController_forTests();
        try {
            if(ruc.deleteUserControllerForTests(user.getUsername()))
            JOptionPane.showMessageDialog(rootPane, "User Deleted Succesfully ! ");
        } catch (NullPointerException ex) {
            JOptionPane.showMessageDialog(rootPane, "User Delete error ! ");
            Logger.getLogger(MainFormStoreOwner_forTests.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jDeleteUserButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFormStoreOwner_forTests.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFormStoreOwner_forTests.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFormStoreOwner_forTests.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFormStoreOwner_forTests.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFormStoreOwner_forTests().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jDeleteUserButton;
    private javax.swing.JButton jEditUserButton;
    private javax.swing.JLabel jL_Username;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jStoreButton;
    private javax.swing.JButton storeManagementBtn;
    // End of variables declaration//GEN-END:variables
}
