/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package blackMidnight.ui_forTests;

import blackMidnight.controller_forTests.DeleteStoreController_forTests;
import blackMidnight.controller_forTests.StoreManagmentController_forTests;
import blackMidnight.model_forTests.Store_Test;
import blackMidnight.util.HibernateUtilTest;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.hibernate.Query;
import org.hibernate.Session;
import org.hibernate.SessionFactory;

/**
 *
 * @author Ilias
 */
public class StoreManagementForm_forTests extends javax.swing.JFrame {

    private static SessionFactory factory = HibernateUtilTest.getSessionFactory();
    private Store_Test myStore = new Store_Test();
    private String username;
    /**
     * Creates new form StoreManagmentForm_forTests
     */
    public StoreManagementForm_forTests() {
        initComponents();
        updateStoresTable();

    }
    public StoreManagementForm_forTests(String username) {
        this.username=username;
        initComponents();
        updateStoresTable();

    }

    private void updateStoresTable() {
        StoreManagmentController_forTests storeManagementController = new StoreManagmentController_forTests();
        List<Store_Test> storesList;
        storesList = storeManagementController.getStores();
        DefaultTableModel deftm = (DefaultTableModel) storeTbl.getModel();

        try {
            for (Store_Test store : storesList) {
                deftm.addRow(new Object[]{store.getNameOfStore(), store.getNumberOfSeats(), store.getStoreAddress(), store.getStoreCity(), store.getStorePhone(), store.getEmail()});
            }
        } catch (Exception e) {
            System.out.println("Connection to Database failed!" + e);
        }

    }
    
    private void getSelectedStore() {
        try {
            int row = storeTbl.getSelectedRow();
            String Table_click = (storeTbl.getModel().getValueAt(row, 0).toString());

            Session session = factory.openSession();
            session.beginTransaction();
            Query query = session.createQuery("from Store_Test where nameOfStore = :nameOfStore");
            query.setString("nameOfStore", Table_click);

            List<Store_Test> stores = (List<Store_Test>) query.list();
            session.getTransaction().commit();
            session.close();

            myStore.setStoreId(stores.get(0).getStoreId());
            myStore.setNameOfStore(stores.get(0).getNameOfStore());
            myStore.setNumberOfSeats(stores.get(0).getNumberOfSeats());
            myStore.setParking(stores.get(0).isParking());
            myStore.setStoreAddress(stores.get(0).getStoreAddress());
            myStore.setStoreCity(stores.get(0).getStoreCity());
            myStore.setStorePhone(stores.get(0).getStorePhone());
            myStore.setOpenDays(stores.get(0).getOpenDays());
            myStore.setOpenHours(stores.get(0).getOpenHours());
            myStore.setEmail(stores.get(0).getEmail());

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        closeBtn = new javax.swing.JButton();
        deleteStoreBtn = new javax.swing.JButton();
        editStoreBtn = new javax.swing.JButton();
        addStoreBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        storeTbl = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        closeBtn.setLabel("Close");
        closeBtn.setName("closeBtn"); // NOI18N
        closeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeBtnMouseClicked(evt);
            }
        });
        closeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeBtnActionPerformed(evt);
            }
        });

        deleteStoreBtn.setLabel("Delete Store");
        deleteStoreBtn.setName("deleteStoreBtn"); // NOI18N
        deleteStoreBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteStoreBtnMouseClicked(evt);
            }
        });
        deleteStoreBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteStoreBtnActionPerformed(evt);
            }
        });

        editStoreBtn.setText("Edit Store");
        editStoreBtn.setName("editStoreBtn"); // NOI18N
        editStoreBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editStoreBtnMouseClicked(evt);
            }
        });
        editStoreBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editStoreBtnActionPerformed(evt);
            }
        });

        addStoreBtn.setText("Add Store");
        addStoreBtn.setName("addStoreBtn"); // NOI18N
        addStoreBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addStoreBtnMouseClicked(evt);
            }
        });
        addStoreBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStoreBtnActionPerformed(evt);
            }
        });

        storeTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Number of seats", "Address", "City", "Phone", "Email"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        storeTbl.setName("storeTbl"); // NOI18N
        storeTbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                storeTblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(storeTbl);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 561, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(closeBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(deleteStoreBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(editStoreBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addStoreBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addStoreBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(editStoreBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(deleteStoreBtn)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addComponent(closeBtn)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeBtnMouseClicked

        try {
            // StoreChooserForReservationForm mainResForm = new StoreChooserForReservationForm();
            MainFormStoreOwner_forTests main = new MainFormStoreOwner_forTests(username);
            main.setVisible(true);
            this.dispose();
        } catch (Exception ex) {
            Logger.getLogger(MainFormStoreOwner_forTests.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_closeBtnMouseClicked

    private void closeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_closeBtnActionPerformed

    private void deleteStoreBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteStoreBtnMouseClicked
        getSelectedStore();

        DeleteStoreController_forTests deleteStore = new DeleteStoreController_forTests();
        boolean successDel = deleteStore.deleteStore(myStore);
        if (successDel == true) {
            JOptionPane.showMessageDialog(rootPane, "Store Deleted Succesfully");
            StoreManagementForm_forTests myForm = new StoreManagementForm_forTests();
            myForm.setVisible(true);
            this.dispose();

        } else {
            JOptionPane.showMessageDialog(rootPane, "Store Failed to Delete!");
        };
    }//GEN-LAST:event_deleteStoreBtnMouseClicked

    private void editStoreBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editStoreBtnMouseClicked

        getSelectedStore();

        EditStoreForm_forTests editStoreF = new EditStoreForm_forTests(myStore);

        try {
            editStoreF.setVisible(true);
            this.dispose();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_editStoreBtnMouseClicked

    private void addStoreBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addStoreBtnMouseClicked
        CreateStoreForm_forTests csform = new CreateStoreForm_forTests(1);
        csform.setVisible(true);
        this.dispose();
        //this.setVisible(false);
    }//GEN-LAST:event_addStoreBtnMouseClicked

    private void storeTblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_storeTblMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_storeTblMouseClicked

    private void addStoreBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStoreBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addStoreBtnActionPerformed

    private void deleteStoreBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteStoreBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteStoreBtnActionPerformed

    private void editStoreBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editStoreBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editStoreBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StoreManagementForm_forTests.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StoreManagementForm_forTests.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StoreManagementForm_forTests.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StoreManagementForm_forTests.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StoreManagementForm_forTests().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addStoreBtn;
    private javax.swing.JButton closeBtn;
    private javax.swing.JButton deleteStoreBtn;
    private javax.swing.JButton editStoreBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable storeTbl;
    // End of variables declaration//GEN-END:variables
}
