/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package blackMidnight.ui;

//import blackMidnight.controller.DeleteItemController;
import blackMidnight.controller.DeleteItemController;
import blackMidnight.controller.IItemManagementController;
import blackMidnight.controller.ItemManagementController;
import blackMidnight.model.Item;
import blackMidnight.util.HibernateUtil;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.hibernate.Query;
import org.hibernate.Session;
import org.hibernate.SessionFactory;
import java.util.logging.Level;
import java.util.logging.Logger;



/**
 *
 * @author Ilias
 */
public class ItemManagementForm extends javax.swing.JFrame {
     private static SessionFactory factory = HibernateUtil.getSessionFactory();
      private Item myItem = new Item();
      private String username;

    /**
     * Creates new form ItemManagmentForm
     */
    public ItemManagementForm() {
        initComponents();
        updateItemTable();
    }
    
     public ItemManagementForm(String username) {
        this.username=username;
        initComponents();
        updateItemTable();

    }
    
     private void updateItemTable() {
        IItemManagementController itemManagementController = new ItemManagementController();
        List<Item> itemsList;
        itemsList = itemManagementController.getItems();
        DefaultTableModel deftm = (DefaultTableModel)jItemTable.getModel();

        try {
            for (Item item  :itemsList) {
                deftm.addRow(new Object[]{item.getItemName(),item.getItemType(), item.getItemPrice(), item.getItemQuantity()});
            }
        } catch (Exception e) {
            System.out.println("Connection to Database failed!" + e);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jAddItemBtn = new javax.swing.JButton();
        jCancel = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jItemTable = new javax.swing.JTable();
        jDeleteBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jAddItemBtn.setText("Add Item");
        jAddItemBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jAddItemBtnMouseClicked(evt);
            }
        });
        jAddItemBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAddItemBtnActionPerformed(evt);
            }
        });

        jCancel.setText("Cancel");
        jCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCancelMouseClicked(evt);
            }
        });
        jCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCancelActionPerformed(evt);
            }
        });

        jItemTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item Name", "Item Type", "Item Price", "Item Quantity"
            }
        ));
        jItemTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jItemTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jItemTable);

        jDeleteBtn.setText("Delete");
        jDeleteBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jDeleteBtnMouseClicked(evt);
            }
        });
        jDeleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDeleteBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jAddItemBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                    .addComponent(jDeleteBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(300, 300, 300)
                        .addComponent(jCancel))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jAddItemBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jDeleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jCancel)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jAddItemBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jAddItemBtnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jAddItemBtnMouseClicked

    private void jAddItemBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAddItemBtnActionPerformed
        // TODO add your handling code here:
        AddItemForm aiform = new AddItemForm(1);
        aiform.setVisible(true);
        this.dispose();
        
       /*    AddItemForm editItemF = new AddItemForm();

        try {
            editItemF.setVisible(true);
            this.dispose();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }*/
    }//GEN-LAST:event_jAddItemBtnActionPerformed

     private void getSelectedItem() {
        try {
            int row = jItemTable.getSelectedRow();
            String Table_click = (jItemTable.getModel().getValueAt(row, 0).toString());

            Session session = factory.openSession();
            session.beginTransaction();
            Query query = session.createQuery("from Item where itemName = :itemName");
            query.setString("itemName", Table_click);

            List<Item> items = (List<Item>) query.list();
            session.getTransaction().commit();
            session.close();

            myItem.setItemId(items.get(0).getItemId());
            myItem.setItemName(items.get(0).getItemName());
            myItem.setItemType(items.get(0).getItemType());
            myItem.setItemPrice(items.get(0).getItemPrice());
            myItem.setItemQuantity(items.get(0).getItemQuantity());
         } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
     }
     
    private void jItemTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jItemTableMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jItemTableMouseClicked

    private void jCancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCancelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jCancelMouseClicked

    private void jCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCancelActionPerformed
        // TODO add your handling code here:
        MainFormStoreOwner main = new MainFormStoreOwner(username);
            main.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_jCancelActionPerformed

    private void jDeleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDeleteBtnActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_jDeleteBtnActionPerformed

    private void jDeleteBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jDeleteBtnMouseClicked
        // TODO add your handling code here:
            getSelectedItem();

        DeleteItemController thisItem = new DeleteItemController();
        boolean successDel = thisItem.deleteItem(myItem);
        if (successDel == true) {
            JOptionPane.showMessageDialog(rootPane, "Item was Deleted Succesfully");
          
           ItemManagementForm myForm = new ItemManagementForm();
       
            myForm.setVisible(true);
            this.dispose();
            
        } else {
            JOptionPane.showMessageDialog(rootPane, "Item Failed to be Deleted!");
        };
    }//GEN-LAST:event_jDeleteBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ItemManagementForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ItemManagementForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ItemManagementForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ItemManagementForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ItemManagementForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jAddItemBtn;
    private javax.swing.JButton jCancel;
    private javax.swing.JButton jDeleteBtn;
    private javax.swing.JTable jItemTable;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
