/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package blackMidnight.ui;

import blackMidnight.DAO.UserDAO;
import blackMidnight.controller.IRegisterUserController;
import blackMidnight.controller.RegisterUserController;
import blackMidnight.model.User;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Ilias
 */
public class MainFormUser extends javax.swing.JFrame {
    static UserDAO ud = new UserDAO();
    private User user ;
    /**
     * Creates new form MainFormStoreOwnerUser
     */
    public MainFormUser() {
        initComponents();
    }
     public MainFormUser(String username) {
        initComponents();
        user = ud.userReturn(ud.userIdReturn(username));
        jL_Username.setText(username);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jL_Username = new javax.swing.JLabel();
        jEditUserButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jChangeReservationButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jReservationButton = new javax.swing.JButton();
        jDeleteUserButton = new javax.swing.JButton();
        jSendQuestion = new javax.swing.JButton();
        showcatalog = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jL_Username.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jL_Username.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jL_Username.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jEditUserButton.setText("Edit User");
        jEditUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEditUserButtonActionPerformed(evt);
            }
        });

        jButton1.setText("Show Reservation History");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jChangeReservationButton.setText("Change Reservation");
        jChangeReservationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChangeReservationButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Welcome ");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jReservationButton.setText("Make A Reservation");
        jReservationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jReservationButtonActionPerformed(evt);
            }
        });

        jDeleteUserButton.setText("Delete User");
        jDeleteUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDeleteUserButtonActionPerformed(evt);
            }
        });

        jSendQuestion.setText("Send your Question");
        jSendQuestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSendQuestionActionPerformed(evt);
            }
        });

        showcatalog.setText("Show Catalog");
        showcatalog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showcatalogActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jL_Username, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jReservationButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jChangeReservationButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(135, 135, 135)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jEditUserButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jDeleteUserButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSendQuestion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(showcatalog, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jL_Username, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(showcatalog, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jReservationButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDeleteUserButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jEditUserButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jChangeReservationButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSendQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jEditUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEditUserButtonActionPerformed
        // TODO add your handling code here:
        EditUserForm euf;
        try {
            euf = new EditUserForm(user);
            euf.setVisible(true);
            this.setVisible(false);
        } catch (NullPointerException ex) {
            Logger.getLogger(MainFormUser.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jEditUserButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        ReservationShowHistoryForm srhform;
        try {
            srhform = new ReservationShowHistoryForm(jL_Username.getText());
            srhform.setVisible(true);
            this.setVisible(false);
        } catch (Exception ex) {
            Logger.getLogger(MainFormUser.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jChangeReservationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChangeReservationButtonActionPerformed
        // TODO add your handling code here:
        try {	
            ReservationChooserForChangeForm reform = new ReservationChooserForChangeForm();
		reform.setVisible(true);
            this.setVisible(false);
        } catch (Exception ex) {
            Logger.getLogger(MainFormUser.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jChangeReservationButtonActionPerformed

    private void jReservationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jReservationButtonActionPerformed
        // TODO add your handling code here:
        StoreChooserForReservationForm crform;
        try {
            crform = new StoreChooserForReservationForm(jL_Username.getText());
            crform.setVisible(true);
            this.setVisible(false);
        } catch (Exception ex) {
            Logger.getLogger(MainFormUser.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jReservationButtonActionPerformed

    private void jDeleteUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDeleteUserButtonActionPerformed
        // TODO add your handling code here:
        IRegisterUserController ruc = new RegisterUserController();
        try {
            if(ruc.deleteUserController(user.getUsername()))
            JOptionPane.showMessageDialog(rootPane, "User Deleted Succesfully ! ");
        } catch (NullPointerException ex) {
            JOptionPane.showMessageDialog(rootPane, "User Delete error ! ");
            Logger.getLogger(MainFormStoreOwner.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jDeleteUserButtonActionPerformed

    private void jSendQuestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSendQuestionActionPerformed
        // TODO add your handling code here:
        CommunicationForm commForm = new CommunicationForm(jL_Username.getText());
        try {
            commForm.setVisible(true);
            this.setVisible(false);
        } catch (NullPointerException ex) {
            Logger.getLogger(MainFormUser.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jSendQuestionActionPerformed

    private void showcatalogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showcatalogActionPerformed
        // TODO add your handling code here:
        ShowItemCatalogForm sicform;
        try {
            sicform = new ShowItemCatalogForm(jL_Username.getText());
            sicform.setVisible(true);
            this.setVisible(false);
        } catch (Exception ex) {
            Logger.getLogger(MainFormUser.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_showcatalogActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFormUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFormUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFormUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFormUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFormUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jChangeReservationButton;
    private javax.swing.JButton jDeleteUserButton;
    private javax.swing.JButton jEditUserButton;
    private javax.swing.JLabel jL_Username;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jReservationButton;
    private javax.swing.JButton jSendQuestion;
    private javax.swing.JButton showcatalog;
    // End of variables declaration//GEN-END:variables
}
