/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package blackMidnight.ui;

import blackMidnight.DAO.UserDAO;
import blackMidnight.controller.IRegisterUserController;
import blackMidnight.controller.RegisterUserController;
import blackMidnight.model.User;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Ilias
 */
public class MainFormStoreOwner extends javax.swing.JFrame {
    static UserDAO ud = new UserDAO();
    static User user ;
    /**
     * Creates new form MainForm
     */
    public MainFormStoreOwner() {
        initComponents();
    }
     public MainFormStoreOwner(String username) {
        initComponents();
        user = ud.userReturn(ud.userIdReturn(username));
        jL_Username.setText(username);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jStoreButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        storeManagementBtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jEditUserButton = new javax.swing.JButton();
        jL_Username = new javax.swing.JLabel();
        jDeleteUserButton = new javax.swing.JButton();
        jitemmanage = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jStoreButton.setText("Add Store");
        jStoreButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jStoreButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Welcome ");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        storeManagementBtn.setText("Store Management");
        storeManagementBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                storeManagementBtnMouseClicked(evt);
            }
        });
        storeManagementBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                storeManagementBtnActionPerformed(evt);
            }
        });

        jButton1.setText("Show Reservation History");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jEditUserButton.setText("Edit User");
        jEditUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEditUserButtonActionPerformed(evt);
            }
        });

        jL_Username.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jL_Username.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jL_Username.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jDeleteUserButton.setText("Delete User");
        jDeleteUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDeleteUserButtonActionPerformed(evt);
            }
        });

        jitemmanage.setText("Manage Item");
        jitemmanage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jitemmanageActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jL_Username, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jitemmanage, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jStoreButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(storeManagementBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jEditUserButton, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDeleteUserButton, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jL_Username, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jStoreButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDeleteUserButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jitemmanage, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(storeManagementBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jEditUserButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jStoreButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jStoreButtonActionPerformed
        // TODO add your handling code here:
        CreateStoreForm csform = new CreateStoreForm();
        csform.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jStoreButtonActionPerformed

    private void storeManagementBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_storeManagementBtnMouseClicked
        // TODO add your handling code here:
        StoreManagmentForm smForm;
        try{
            smForm = new StoreManagmentForm(jL_Username.getText());
            smForm.setVisible(true);
            this.setVisible(false);
        }catch(Exception ex){
            Logger.getLogger(MainFormStoreOwner.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_storeManagementBtnMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        ReservationShowHistoryForm srhform;
        try {
            srhform = new ReservationShowHistoryForm();
            srhform.setVisible(true);
            this.setVisible(false);
        } catch (Exception ex) {
            Logger.getLogger(MainFormStoreOwner.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jEditUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEditUserButtonActionPerformed
        // TODO add your handling code here:
        EditUserForm euf;
        try {
            euf = new EditUserForm(user);
            euf.setVisible(true);
            this.setVisible(false);
        } catch (NullPointerException ex) {
            Logger.getLogger(MainFormStoreOwner.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jEditUserButtonActionPerformed

    private void jDeleteUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDeleteUserButtonActionPerformed
        // TODO add your handling code here:
        IRegisterUserController ruc = new RegisterUserController();
        try {
            if(ruc.deleteUserController(user.getUsername()))
                JOptionPane.showMessageDialog(rootPane, "User Deleted Succesfully ! ");
        } catch (NullPointerException ex) {
            JOptionPane.showMessageDialog(rootPane, "User Delete error ! ");
            Logger.getLogger(MainFormStoreOwner.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jDeleteUserButtonActionPerformed

    private void storeManagementBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_storeManagementBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_storeManagementBtnActionPerformed

    private void jitemmanageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jitemmanageActionPerformed
        // TODO add your handling code here:
         ItemManagementForm csForm = new ItemManagementForm();
      //  csform.setVisible(true);
      //  this.setVisible(false);
        
        
        try{
            csForm = new ItemManagementForm(jL_Username.getText());
            csForm.setVisible(true);
            this.setVisible(false);
        }catch(Exception ex){
            Logger.getLogger(MainFormStoreOwner.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jitemmanageActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFormStoreOwner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFormStoreOwner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFormStoreOwner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFormStoreOwner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFormStoreOwner().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jDeleteUserButton;
    private javax.swing.JButton jEditUserButton;
    private javax.swing.JLabel jL_Username;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jStoreButton;
    private javax.swing.JButton jitemmanage;
    private javax.swing.JButton storeManagementBtn;
    // End of variables declaration//GEN-END:variables
}
