/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package blackMidnight.ui;

import blackMidnight.controller.IStoreChooserForReservationController;
import blackMidnight.controller.StoreChooserForReservationController;
import blackMidnight.model.Store;
import blackMidnight.ui.CreateReservationForm;
import javax.swing.*;
import java.io.File;
import java.util.ArrayList;
import java.util.List;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Ilias
 * 
 */
public class StoreChooserForReservationForm extends javax.swing.JFrame{

    /**
     * Creates new form ReservationForm
     * This form is the first stage for creating a new reservation. Here we
     * choose one of the existing stores.We keep the name and by clicking 
     * create reservation button we entering the final stage where we send the 
     * chosen store name from this form.
     */
    public StoreChooserForReservationForm() throws Exception {
        initComponents();
        Update_Table();
    }
    public StoreChooserForReservationForm(String username) throws Exception {
        initComponents();
        usernameText.setText(username);
        Update_Table();
    }
    
     /**
     * Update_Table : Here we load the stores informations for helping the
     * client to choose the store he prefers.
     *  TO DO: chosing category and showing only the stores of that category
     * to the table for easier choosing
     */
    private void Update_Table() throws Exception{
        IStoreChooserForReservationController storeChooserForReservation = new StoreChooserForReservationController();
           
        List<Store> stores;
        stores = storeChooserForReservation.getStores();
        DefaultTableModel dt = (DefaultTableModel)Stores.getModel();
        
        try{ 
            for(Store store : stores){
                dt.addRow(new Object[]{store.getNameOfStore(),store.getNumberOfSeats(),store.getStoreAddress(),store.getStorePhone()});
            }
            
            
        }catch (Exception e){
           System.out.println("Connection to Store Database failed!"+e);
        }
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Stores = new javax.swing.JTable();
        CreateReservation = new javax.swing.JButton();
        CancelReservation = new javax.swing.JButton();
        storeText = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        storeInformationsText = new javax.swing.JTextArea();
        openHourslbl = new javax.swing.JLabel();
        storeNamelbl = new javax.swing.JLabel();
        openHoursText = new javax.swing.JTextField();
        usernameText = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Stores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Store Name", "Available Seats", "Address", "Telephone"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        Stores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                StoresMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Stores);

        CreateReservation.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        CreateReservation.setText("Create Reservation");
        CreateReservation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateReservationActionPerformed(evt);
            }
        });

        CancelReservation.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        CancelReservation.setText("Cancel Reservation");
        CancelReservation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelReservationActionPerformed(evt);
            }
        });

        storeInformationsText.setColumns(20);
        storeInformationsText.setRows(5);
        jScrollPane2.setViewportView(storeInformationsText);

        openHourslbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        openHourslbl.setText("Open Hours");

        storeNamelbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        storeNamelbl.setText("Store's name");

        usernameText.setEnabled(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Username");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(CreateReservation, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CancelReservation, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(openHourslbl, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(openHoursText))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(storeNamelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(storeText, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(308, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(usernameText, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(364, 364, 364))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CreateReservation, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CancelReservation, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(openHourslbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(openHoursText, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(storeNamelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(storeText, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * CreateReservationActionPerformed : Here we calling the 
     * CreateReservationFinalForm by sending the chosen store's name
     */
    private void CreateReservationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateReservationActionPerformed
        
        //CreateReservationForm rFormFinal = new CreateReservationForm(storeText.getText().toString());
        CreateReservationForm rFormFinal = new CreateReservationForm(storeText.getText().toString(),openHoursText.getText().toString(),usernameText.getText());
        
        if(storeText.getText().toString().equals("")){
            JOptionPane.showMessageDialog(null, "You haven't selected a store name!");
        } else{
            rFormFinal.setVisible(true);
            this.dispose();
        }
        
        
        try {
            Update_Table();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null,ex);
        }
        
    }//GEN-LAST:event_CreateReservationActionPerformed

    /**
     * StoresMouseClicked : Here by clicking the store we want to make the reservation 
     * send's the name of the store to the storeText. and loads that store's informations to the text field
     */
    private void StoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StoresMouseClicked
        
        try{
            IStoreChooserForReservationController storeDetails = new StoreChooserForReservationController();
            int row = Stores.getSelectedRow();
            String Table_click = (Stores.getModel().getValueAt(row,0).toString());
            storeText.setText(Table_click);
            
            List<Store> storeInformations = new ArrayList<Store>();
            List<Store> storeOpenHours = new ArrayList<Store>();
            
            storeInformations = storeDetails.getStoreDetails(Stores.getModel().getValueAt(row,0).toString(), Stores.getModel().getValueAt(row,2).toString());
            storeInformationsText.setText(storeInformations.iterator().next().getStoreDetails().toString());
            storeOpenHours = storeDetails.getStoresOpenHours(Stores.getModel().getValueAt(row,0).toString(), Stores.getModel().getValueAt(row,2).toString());
            openHoursText.setText(storeOpenHours.iterator().next().getOpenHours().toString());
        }catch (Exception e){
            JOptionPane.showMessageDialog(null,e);
            
        }
    }//GEN-LAST:event_StoresMouseClicked

    private void CancelReservationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelReservationActionPerformed
        // TODO add your handling code here:
        try {
            MainFormUser main = new MainFormUser(usernameText.getText());
            main.setVisible(true);
            this.dispose();
        } catch (Exception ex) {
            Logger.getLogger(CreateReservationForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_CancelReservationActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StoreChooserForReservationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StoreChooserForReservationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StoreChooserForReservationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StoreChooserForReservationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {                                                     
                try {
                    new StoreChooserForReservationForm().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(StoreChooserForReservationForm.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelReservation;
    private javax.swing.JButton CreateReservation;
    private javax.swing.JTable Stores;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField openHoursText;
    private javax.swing.JLabel openHourslbl;
    private javax.swing.JTextArea storeInformationsText;
    private javax.swing.JLabel storeNamelbl;
    private javax.swing.JTextField storeText;
    private javax.swing.JTextField usernameText;
    // End of variables declaration//GEN-END:variables
}
